# fly.toml app configuration file generated for elgolazof5 on 2025-07-11T15:46:52-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'elgolazof5'
primary_region = 'eze'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
