const result = {
  accounts_info: null,
  acquirer_reconciliation: [],
  additional_info: {
    ip_address: '190.183.252.68',
    items: [[Object]],
    payer: { first_name: 'Cristian' },
    tracking_id: 'platform:v1-blacklabel,so:ALL,type:N/A,security:none'
  },

  authorization_code: null,
  binary_mode: false,
  brand_id: null,
  build_version: '3.113.0-rc-2',
  call_for_authorize_id: null,
  captured: true,
  card: {},
  charges_details: [
    {
      accounts: [Object],
      amounts: [Object],
      client_id: 0,
      date_created: '2025-07-06T23:50:43.000-04:00',
      id: '117173473089-001',
      last_updated: '2025-07-06T23:50:43.000-04:00',
      metadata: [Object],
      name: 'mercadopago_fee',
      refund_charges: [],
      reserve_id: null,
      type: 'fee'
    }
  ],
  charges_execution_info: {
    internal_execution: {
      date: '2025-07-06T23:50:43.431-04:00',
      execution_id: '01JZHG3TXGM0C0D0MCTN7T65ZK'
    }
  },
  collector_id: 2513632303,
  corporation_id: null,
  counter_currency: null,
  coupon_amount: 0,
  currency_id: 'ARS',
  date_approved: '2025-07-06T23:50:43.000-04:00',
  date_created: '2025-07-06T23:50:43.000-04:00',
  date_last_updated: '2025-07-06T23:50:43.000-04:00',
  date_of_expiration: null,
  deduction_schema: null,
  description: 'El Golazo F5 - Turno',
  differential_pricing_id: null,
  external_reference: 'reserva_1751860229116',
  fee_details: [{ amount: 123, fee_payer: 'collector', type: 'mercadopago_fee' }],
  financing_group: null,
  id: 117173473089,
  installments: 1,
  integrator_id: null,
  issuer_id: '2005',
  live_mode: true,
  marketplace_owner: null,
  merchant_account_id: null,
  merchant_number: null,
  metadata: {},
  money_release_date: '2025-07-24T23:50:43.000-04:00',
  money_release_schema: null,
  money_release_status: 'pending',
  notification_url: 'https://e958-190-124-63-68.ngrok-free.app/webhook',
  operation_type: 'regular_payment',
  order: { id: '32257111930', type: 'mercadopago' },
  payer: {
    email: 'test_user_358990658@testuser.com',
    entity_type: null,
    first_name: null,
    id: '2513632315',
    identification: { number: '1111111', type: 'DNI' },
    last_name: null,
    operator_id: null,
    phone: { number: null, extension: null, area_code: null },
    type: null
  },
  payment_method: { id: 'account_money', issuer_id: '2005', type: 'account_money' },
  payment_method_id: 'account_money',
  payment_type_id: 'account_money',
  platform_id: null,
  point_of_interaction: {
    application_data: { name: 'checkout-off', operating_system: null, version: 'v2' },
    business_info: {
      branch: 'Merchant Services',
      sub_unit: 'checkout_pro',
      unit: 'online_payments'
    },
    transaction_data: { e2e_id: null },
    type: 'CHECKOUT'
  },
  pos_id: null,
  processing_mode: 'aggregator',
  refunds: [],
  release_info: null,
  shipping_amount: 0,
  sponsor_id: null,
  statement_descriptor: null,
  status: 'approved',
  status_detail: 'accredited',
  store_id: null,
  tags: null,
  taxes_amount: 0,
  transaction_amount: 3000,
  transaction_amount_refunded: 0,
  transaction_details: {
    acquirer_reference: null,
    external_resource_url: null,
    financial_institution: null,
    installment_amount: 0,
    net_received_amount: 2877,
    overpaid_amount: 0,
    payable_deferral_period: null,
    payment_method_reference_id: null,
    total_paid_amount: 3000
  },
}